
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: managerapp
  labels:
    app: managerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managerap
  template:
    metadata:
      labels:
        app: managerapp 
    spec:
      containers:
      - name: managerappserver
        image: tauqeerdocker/managerapp:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: managerapp-service
spec:
  selector:
    app: managerapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
